version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2023-05-18T00-05-36Z
    container_name: lab1_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    restart: unless-stopped

  web:
    build: .
    container_name: lab1_django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - minio
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

volumes:
  minio_data: