# Generated by Django 4.2.25 on 2025-10-08 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удален'), ('formed', 'Сформирован'), ('completed', 'Завершен'), ('rejected', 'Отклонен')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('formed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('client_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО клиента')),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон клиента')),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email клиента')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Наличные'), ('mortgage', 'Ипотека'), ('installment', 'Рассрочка')], max_length=50, null=True, verbose_name='Способ оплаты')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итоговая стоимость')),
                ('estimated_delivery_date', models.DateField(blank=True, null=True, verbose_name='Предполагаемая дата доставки документов')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderated_orders', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус (действует/удален)')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
                ('image_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключ изображения в Minio')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Площадь (кв.м)')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('rooms', models.PositiveIntegerField(default=1, verbose_name='Количество комнат')),
                ('floor', models.PositiveIntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('total_floors', models.PositiveIntegerField(blank=True, null=True, verbose_name='Всего этажей')),
                ('property_type', models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('commercial', 'Коммерческая недвижимость'), ('land', 'Земельный участок')], max_length=50, verbose_name='Тип недвижимости')),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
            },
        ),
        migrations.CreateModel(
            name='OrderRealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order_number', models.PositiveIntegerField(default=1, verbose_name='Порядковый номер')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основной объект')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка (%)')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Финальная цена')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.order', verbose_name='Заявка')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.realestate', verbose_name='Объект недвижимости')),
            ],
            options={
                'verbose_name': 'Объект недвижимости в заявке',
                'verbose_name_plural': 'Объекты недвижимости в заявках',
                'unique_together': {('order', 'real_estate')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='properties',
            field=models.ManyToManyField(through='services.OrderRealEstate', to='services.realestate', verbose_name='Объекты недвижимости'),
        ),
    ]
